# host / ip address of the parent controller
parent_host: "parent"

# custom name for the node
node_id: "local-node"

# port of the parent controller host
# default: 8008
parent_port: "8008"

# port to map to
port: "9123"

# ip where the node is accessible from
own_ip: "node"

# port where the node is accessible from
own_port: "9123"

# api key, needs to be exactly the same as the node

API_KEY: "037gMn6oTXrE9VWjYRDG"

# just a randomly generated key, comment the line, if you want to disable the feature
# you also need to comment the line in the configuration for the parent node
