scanner:
    diff_only: False  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle  # Other option is flake8

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 120  # Default is 79 in PEP 8
    ignore:  # Errors and warnings to ignore
        - W503  # line break before binary operator
        - W504  # line break after binary operator
        - E731  # do not assign a lambda expression, use a def
        - C406  # Unnecessary list literal - rewrite as a dict literal.
        - E741  # ambiguous variable name
        - E126
        - E121
        - E123
        - E226
        - E231
        - W291
        - E203

no_blank_comment: True
descending_issues_order: False
