language: python

python:
    - "3.7"

services:
    - docker

before_install:
    - bash travis/install_travis.sh

script:
    - bash travis/run_travis.sh

deploy:
    provider: releases
    api_key: $GITHUB_KEY
    file:
        - node/node
    draft: true
    on:
        branch: master
    cleanup: false
