language: python

services:
    - docker

before_install:
    - bash travis/install_travis.sh

script:
    - bash travis/run_travis.sh

deploy:
    provider: releases
    token: $GITHUB_KEY
    file:
        - youtube/node/node
    draft: true
    on:
        branch: master
    cleanup: false