version: '2.4'
services:
    discord:
        build:
            context: src/
            dockerfile: Dockerfile
        restart: always
        working_dir: /usr/src/app/
        command: python -u src/discord_main.py
        volumes:
            - .:/usr/src/app/
        env_file:
            - sysenv.env
        stop_grace_period: 15s
        ports:
            - 9988:9988
        networks:
            - web
        init: true
        stdin_open: true
        tty: true
    web:
        hostname: web
        build:
            context: web/
            dockerfile: Dockerfile
        command: sh -c "cd /usr/src/app/ && python -u server.py"
        volumes:
            - ./web/:/usr/src/app
        env_file:
            - sysenv.env
        networks:
            - web
        labels:
            - traefik.frontend.rule=Host:f.chulte.de,d.chulte.de;PathPrefix:/
            - traefik.enable=true
            - traefik.frontend.priority=5
            - traefik.port=80
    node:
        build: node/
        working_dir: /home/src/app/
        command: /wait.sh -t 0 discord:9988 -- python node.py
        restart: always
        volumes:
            - ./node/:/home/src/app
        environment:
            - PYTHONUNBUFFERED=TRUE
        networks:
            - web
        init: true

networks:
    web:
        external: true
