version: '3'
services:
    discord:
        build: .
        command: sh -c "cd /usr/src/app && python -u discord/discord_main.py"
        volumes:
            - .:/usr/src/app/
        env_file:
            - sysenv.txt
        stop_grace_period: 15s
        depends_on:
          - database
    web:
        build:
            context: .
            dockerfile: Dockerfile_b
        command: sh -c "cd /usr/src/app/stats/ && gunicorn stats.wsgi -b 0.0.0.0:8001"
        volumes:
            - .:/usr/src/app
        ports:
            - "8001:8001"
        env_file:
            - sysenv.txt
        depends_on:
          - database
    database:
        image: mvertes/alpine-mongo
        volumes:
          - ./mongodb:/data/db