version: '2.4'
services:
    discord:
        build:
            context: discord/
            dockerfile: Dockerfile
        restart: always
        working_dir: /usr/src/app/
        command: python -u discord/discord_main.py
        volumes:
            - .:/usr/src/app/
        env_file:
            - sysenv.env
        stop_grace_period: 15s
        networks:
            - web
        init: true
        stdin_open: true
        tty: true
    web:
        hostname: web
        build:
            context: web/
            dockerfile: Dockerfile
        command: sh -c "cd /usr/src/app/ && python -u server.py"
        volumes:
            - ./web/:/usr/src/app
        env_file:
            - sysenv.env
        networks:
            - web
        labels:
            - traefik.frontend.rule=Host:f.chulte.de,d.chulte.de;PathPrefix:/
            - traefik.enable=true
            - traefik.frontend.priority=5
            - traefik.port=80
    node:
        build: youtube/node
        working_dir: /home/src/app/
        #command: "python3 -u node.py"
        command: gunicorn node:app -k gevent --worker-connections 1000 --preload --bind=0.0.0.0:9123 --capture-output
        restart: always
        depends_on:
            - parent
        volumes:
            - ./youtube/node/:/home/src/app
        env_file:
            - youtube/node/settings.env
        environment:
            - PYTHONUNBUFFERED=TRUE
        networks:
            - web
        init: true
    parent:
        build: youtube
        working_dir: /home/src/app/
        command: "python3 -u parent.py"
        restart: always
        volumes:
            - ./youtube/:/home/src/app
        env_file:
            - youtube/settings.env
        networks:
            - web
        ports:
            - 9988:9988
        init: true
networks:
    web:
        external: true
