version: '2'
services:
    discord:
        build: .
        command: sh -c "cd /usr/src/app && python -u discord/discord_main.py"
        volumes:
            - .:/usr/src/app/
        env_file:
            - sysenv.txt
        stop_grace_period: 15s
        stop_signal: SIGTERM
    web:
        build:
            context: .
            dockerfile: Dockerfile_b
        command: sh -c "cd /usr/src/app && python stats/manage.py migrate && cd ./stats/ && python3 manage.py runserver 0.0.0.0:8001"
        volumes:
            - .:/usr/src/app
        ports:
            - "8001:8001"
        env_file:
            - sysenv.txt
