# host / ip address of the parent controller
parent_host: "discord"

# port of the parent controller host
# default: 9988
parent_port: "9988"

# api key, needs to be exactly the same as the node

# API_KEY: "037gMn6oTXrE9VWjYRDG"

# just a randomly generated key, comment the line, if you want to disable the feature
# you also need to comment the line in the configuration for the parent node
